Competition.App/Competition.App.Web/Controllers/CompetitionsController.cs
using Competition.App.Common.ViewModels.Competition;
using Competition.App.Services.CompetitionServices;
using Competition.App.Services.TeamsServices;
using System.Web.Mvc;

namespace Competition.App.Web.Controllers
{
    public class CompetitionsController : Controller
    {
        private readonly ICompetitionServices _competitionService;
        private readonly ITeamsServices _teamsService;


        public CompetitionsController(ICompetitionServices competitionService, ITeamsServices teamsServices)
        {
            _competitionService = competitionService;
            _teamsService = teamsServices;
        }

        [HttpGet]
        // GET: Competitions
        public ActionResult Index()
        {
            var competitons = _competitionService.GetAll();

            return View(competitons);
        }

        [HttpGet]
       public ActionResult Create ()
        {
            var teams = _teamsService.GetAllTeams();

            var model = new CompetitionViewModel();
            model.Teams = teams;

            return View(model);
        }

        [HttpPost]
        public JsonResult Create(CompetitionViewModel model)
        {
            try
            {
                _competitionService.Create(model);

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                
            }
            catch (System.Exception ex)
            {
                // Handle and log the error 
                throw;
            }
        }

        [HttpPost]
        public JsonResult Delete(int competitionId)
        {
            try
            {
                _competitionService.Delete(competitionId);

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);

            }
            catch (System.Exception ex)
            {
                // Handle and log the error 
                throw;
            }
        }

        [HttpGet]        
        public ActionResult Standings (int competitionId)
        {
            try
            {
                var standings = _competitionService.GetStandings(competitionId);

                return View(standings);
            }
            catch (System.Exception)
            {

                // Handle and log the error 
                throw;
            }
        }
    }
}

Competition.App/Competition.App.Web/Controllers/HomeController.cs
using Competition.App.Services.HomeService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Competition.App.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;


        public HomeController(IHomeService homeService)
        {
            _homeService = homeService;
        }

        public ActionResult Index()
        {
            var homeStats = _homeService.getDashBoardStats();

            return View(homeStats);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Competition.App/Competition.App.Web/Controllers/MatchesController.cs
using Competition.App.Common.ViewModels.Matches;
using Competition.App.Domain.Entities;
using Competition.App.Domain.Repository;
using Competition.App.Services.MatchServices;
using Competition.App.Services.ModelFactory;
using Competition.App.Web.CustomFilters;
using System;
using System.Web.Mvc;


namespace Competition.App.Web.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IRepository _repository;
        private readonly IModelsFactory _modelsFactory;
        private readonly IMatchServices _matchServices;

        public MatchesController(IRepository repository, IModelsFactory modelsFactory , IMatchServices matchServices)
        {
            _repository = repository;
            _modelsFactory = modelsFactory;
            _matchServices = matchServices;

        }

        // GET: Matches
        public ActionResult Index(int competitionId)
        {
            var matches = _matchServices.GetAllMatches();
            ViewBag.CompatitionId = competitionId;

            return View(matches);
        }

        [HttpGet]
        public ActionResult CreateMatch(int competitionId)
        {
            var matchModel = new MatchesViewModel { CompetitionId = competitionId };
            return View(matchModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult CreateMatch(MatchesViewModel model)
        {
            try
            {
                var teamModel = _modelsFactory.CreateMatchEntity(model);

                _repository.Insert(teamModel);
                _repository.Save();

                return RedirectToAction("Index", new { competitionId = model.CompetitionId });
            }
            catch (Exception)
            {

                throw;
            }
        }

        [AjaxValidateAntiForgeryToken]
        public JsonResult DeleteMatch(int matchId)
        {
            try
            {
                var match = _repository.GetById<Matches>(matchId);

                if (match != null)
                {
                    _repository.Delete(match);
                    _repository.Save();

                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [AjaxValidateAntiForgeryToken]
        public JsonResult SaveResult (int homeScore, int awayScore, int matchId)
        {
            try
            {
                 _matchServices.SaveResult(homeScore, awayScore, matchId);


                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
         
        }


    }
}

Competition.App/Competition.App.Web/Controllers/TeamsController.cs
using Competition.App.Common.ViewModels.Teams;
using Competition.App.Services.TeamsServices;
using System;
using System.Web.Mvc;

namespace Competition.App.Web.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ITeamsServices _teamServices;

        public TeamsController(ITeamsServices teamsServices)
        {
            _teamServices = teamsServices;
        }


        [HttpGet]
        public ActionResult Index()
        {
            var teams = _teamServices.GetAllTeams();
            return View(teams);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TeamsViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _teamServices.CreateTeam(model);

                    return RedirectToAction("Index");
                }

                return View(model);
            }
            catch (Exception)
            {
                // Handle and log the exception
                throw;
            }
        }

        [HttpGet]
        public ActionResult Edit (int teamId)
        {
            try
            {
                var team = _teamServices.GetById(teamId);

                return View(team);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Edit (TeamsViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _teamServices.EditTeam(model);

                    return RedirectToAction("Index");
                }

                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public JsonResult DeleteTeam (int teamId)
        {
            try
            {
                _teamServices.Delete(teamId);

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                // Handle and log exception
                throw;
            }
        }

    }
}

Competition.App/Competition.App.Web/Views/Competitions/Create.cshtml
@model Competition.App.Common.ViewModels.Competition.CompetitionViewModel
@using Competition.App.Web.WebHelpers
@{
    ViewBag.Title = "Create";
}

<h2>Create competition</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.CompetitionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompetitionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompetitionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div>
            @Html.DropDownList("Teams", SelectedListExtension.GetAllTeams())
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5 ">
                <a href="#" onclick="createCompetition();return false" class="btn btn-success pull-right"> Create</a>
                <a href="@Url.Action("Index","Competitions")" class="btn btn-danger pull-right"> Cancel</a>

            </div>
        </div>
    </div>
}
<link href="~/Content/dual-listbox.css" rel="stylesheet" />
<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/dual-listbox.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script>
        const dualListbox = new DualListbox('select', {
            availableTitle: 'Teams',
            selectedTitle: 'Selected teams',
        });

        function createCompetition() {

            if ($('#CompetitionName').val() == '') {
                toastr.error("Competition name is required");
                return false;
            }

            if ($('.dual-listbox__selected >li').length < 2) {
                toastr.warning('Please select at least 2 competitors');
                return false;
            }


            var teams = new Array();

            $('.dual-listbox__selected >li').each(function (i, li) {
                teams.push($(li).attr('data-id'));
            });

            $.ajax({
                url: '@Url.Action("Create","Competitions")',
                type: 'POST',
                traditional: true,
                data: { CompetitionName: $('#CompetitionName').val(), TeamIds: teams },
                success: function (data) {
                    if (data.success) {
                        window.location.href = "/Competitions/Index";
                    }
                },
                error: function (err) {
                    toastr.error('Cannot create the competition');
                    console.log(err);
                }
            });

        }

    </script>
}

Competition.App/Competition.App.Web/Views/Competitions/Index.cshtml
@model IEnumerable<Competition.App.Common.ViewModels.Competition.CompetitionViewModel>

@{
    ViewBag.Title = "Index";
}

    <div class="competition-contaier">
        <p>
            <a class="btn btn-info" href="@Url.Action("Create","Competitions")"><i class="fa fa-plus"></i> Add new</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CompetitionName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateStarted)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="competitons-body">
                @foreach (var item in Model)
                {
                    <tr id="@item.CompetitionId">
                        <td>
                            @Html.DisplayFor(modelItem => item.CompetitionName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateStarted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            <a href="@Url.Action("Standings","Competitions",new {competitionId = item.CompetitionId })" class="btn btn-xs btn-info"><i class="fa fa-list"></i> Standings</a>
                            <a href="@Url.Action("Index","Matches",new {competitionId = item.CompetitionId })" class="btn btn-xs btn-warning"><i class="fa fa-calendar"></i> Fixtures</a>
                            <a class="btn btn-xs btn-danger" onclick="removeCompetition(@item.CompetitionId); return false"><i class="fa fa-trash-o"></i> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>

<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    <script src="~/Scripts/toastr.min.js"></script>
    <script>
        function removeCompetition(competitionId) {
            $.ajax({
                url: '@Url.Action("Delete","Competitions")',
                type : 'POST',
                data: { competitionId: competitionId },
                success: function (data) {
                    if (data.success) {
                        $('#competitons-body').find('#' + competitionId).remove();
                        toastr.success("Successfully deleted competition");
                    } else {
                        toastr.error("Failed to delete competiton");
                    }
                },
                error: function (err) {
                    console.log(err);
                    toastr.error("Failed to delete competiton");
                }
            })
        }
    </script>
}

Competition.App/Competition.App.Web/Views/Competitions/Standings.cshtml
@model Competition.App.Common.ViewModels.Competition.CompetitionStandingsViewModel

@{
    ViewBag.Title = "Standings";
}

<h2>@Model.CompetitionName Standings</h2>


<table class="table">
    <tr>
        <th>
            Team
        </th>
        <th>
            Points
        </th>
    </tr>

@foreach (var item in Model.Items) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TeamName)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Points)
    </td>
</tr>
}

</table>

Competition.App/Competition.App.Web/Views/Home/Index.cshtml
@model Competition.App.Common.ViewModels.Home.DashboardResultsViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p>Competition APP </p>
    <a href="#" data-toggle="modal" data-target="#Rules"><i class="fa fa-gamepad" data-toggle="modal" data-target="#Rules"></i>Rules</a>
</div>

<div>
    <div>
        Active Competitions :  @Model.ActiveCompettions
    </div>
    <div>
        Active Teams :  @Model.ActiveTeams
    </div>
    <div>
        Open Matches :  @Model.MatchesInProgress
    </div>
    <div>
        Match Results :  @Model.MatchResults
    </div>
</div>
@Html.Partial("~/Views/Partials/_rules.cshtml")

Competition.App/Competition.App.Web/Views/Matches/CreateMatch.cshtml
@model Competition.App.Common.ViewModels.Matches.MatchesViewModel
@using Competition.App.Web.WebHelpers
@{
    ViewBag.Title = "CreateMatch";
}

<h2>New match</h2>

@using (Html.BeginForm("CreateMatch", "Matches", FormMethod.Post, new { @id = "match-form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x=>x.CompetitionId)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.HomeTeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.HomeId, SelectedListExtension.GetAllTeams(), "Select home team", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HomeId, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AwayTeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.AwayId, SelectedListExtension.GetAllTeams(), "Select away team", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AwayId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StartTime, new { @type = "datetime-local", @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
        $('#match-form').submit(function (e) {
            debugger;
            if ($('#HomeId').val() === $('#AwayId').val()) {
                toastr.warning('Home and away team must be different teams');
                e.preventDefault();
                return false;
            }
        });
    </script>
}

Competition.App/Competition.App.Web/Views/Matches/Index.cshtml
@model IEnumerable<Competition.App.Common.ViewModels.Matches.MatchesViewModel>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("CreateMatch","Matches", new { competitionId = ViewBag.CompatitionId})">Create match</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeTeamName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AwayTeamName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Result)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Finished)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="matches-table">
        @foreach (var item in Model)
        {
            <tr id="@item.MatchId">
                <td>
                    @Html.DisplayFor(modelItem => item.StartTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomeTeamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AwayTeamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Result)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Finished)
                </td>
                <td>
                    @if (!item.Finished)
                    {
                        <a class="btn btn-xs btn-info" onclick="enterResult('@item.HomeTeamName','@item.AwayTeamName','@item.MatchId' )"><i class="fa fa-pencil"></i>Enter result</a>
                        <a href="#" onclick="deleteMatch(@item.MatchId)" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<!-- Trigger the modal with a button -->
@*<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#enter-result-modal">Open Modal</button>*@

@Html.Partial("~/Views/Partials/_enterResultView.cshtml")
<input type="hidden" id="forgeryToken" value="@HtmlHelpers.GetAntiForgeryToken()" />

@section Scripts  {
    <script>
        function deleteMatch(matchId) {
            $.ajax({
                url: '@Url.Action("DeleteMatch","Matches")',
                data: { matchId: matchId },
                headers: {
                    'VerificationToken': $("#forgeryToken").val()
                },
                success: function (data) {
                    if (data.success) {
                        $('#matches-table').find(`#${matchId}`).remove();
                        toastr.success('Match has been deleted');
                    }
                    else
                        toastr.error('Match has not been deleted');
                }
            });
        }

        function enterResult(homeTeam, awayTeam, matchId) {            
            $('#homeTeam').text(homeTeam);
            $('#awayTeam').text(awayTeam);
            $('#matchId').text(matchId);
            $('#enter-result-modal').modal('show');
        }

   
       
    </script>
}

Competition.App/Competition.App.Web/Views/Partials/_enterResultView.cshtml
<!-- Modal -->
<div id="enter-result-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <span id="matchId" style="display:none"></span>
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Enter result</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <label id="homeTeam" class="col-md-3"></label>
                        <input type="number" id="homeScore" class="col-md-2" />
                        <label class="col-md-1">:</label>
                        <input type="number" id="awayScore" class="col-md-2" />
                        <label id="awayTeam" class="col-md-3"></label>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal" onclick="saveResult();">Save</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<script>
    function saveResult() {
        debugger;
        var homeTeamScore = $('#homeScore').val();
        var awayTeamScore = $('#awayScore').val();
        var matchId = $('#matchId').text();
            $.ajax({
                 url: '@Url.Action("SaveResult","Matches")',
                data: { homeScore: homeTeamScore, awayScore: awayTeamScore, matchId: matchId },
                method : 'POST',
                headers: {
                    'VerificationToken': $("#forgeryToken").val()
                },
                success: function (data) {
                    if (data.success) {                       
                        toastr.success('Result has been saved');
                    }
                    else
                        toastr.error('Result was not been saved');
                }
            });        
        }
</script>

Competition.App/Competition.App.Web/Views/Partials/_rules.cshtml
    <div id="Rules" class="modal fade" role="dialog">
        <div class="modal-dialog">          
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Competitions rules</h4>
                </div>
                <div class="modal-body">
                    The winner gains 3 points, loser 0 points , if the match end as a draw both teams will gain 1 point
                </div>
                <div class="modal-footer">                   
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

Competition.App/Competition.App.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index","Home")">
                            
                            <img class="menu-icon" src="~/Content/home.png" />  Home
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Competitions")">
                            <img class="menu-icon" src="~/Content/icons8-world-cup-50.png" /> Competitions
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Teams")">

                            <img class="menu-icon" src="~/Content/icons8-teams-50.png" />  Teams
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>